### ISSUE TITLE
suggestion:dolt should be like a  jbdc

### ISSUE THREAD

**Issue by GodGavin** [liquidata-inc/dolt#669]
dolt should be like a  jbdc ,you can use dolt to git-like operte mysql database and other databases;but if you combine mysql with git,it may diffcult and unstable;
this is my  unconsidered idea,may dolt better.

**Comment by oscarbatori** [comment]
@GodGavin thanks for your input, apologies for the delayed response.

The issue here is... that's not really possible. The core of the problem is the underlying storage format. MySQL is optimized for some combination of query performance and compression. That makes structural sharing across versions prohibitively expensive. 

We think we are doing a pretty good job on stability. Have you had the chance to try the tool out? Do you have a use-case in mind?
