### ISSUE TITLE
[Question] What size of data can dolt handle?

### ISSUE THREAD

**Issue by qiuwei** [liquidata-inc/dolt#852]
I just came into this very interesting project and have some questions.
1. What size of data can dolt handle? Can it handle data of terabyte size?
2. Is it possible to have a retention policy for the commits? For example, we might want to truncate all commits before certain commit just to save disk space.
3. I noticed dolt has a nice feature to synchronize a mysql database to a dolt database. I am wondering whether the dolt database tracks all of the changes in the original database as commits, or just takes some snapshots of the original database.

Thanks in advance!

**Comment by oscarbatori** [comment]
@qiuwei thanks for your thoughtful questions and showing interest in Dolt. We think it's pretty interesting too!

In order the order of your questions:
1. Dolt currently works only a single machine. We have had repos of around 100GB, so the limit is what disk and memory can handle on a single machine. We have also provisioned machines on Amazon for large operations. We think the data model lends itself to distributed storage, and we anticipate building that in the medium term.
2. No, it's currently not, but we might introduce something like that in the future in the form of a squash type feature. Dolt stores deltas efficiently so unless this is pathological case the storage footprint is roughly equivalent to the information density.
3. If you are referring to the Doltpy tools for sync, it currently takes a snapshot whenever you prompt it to do so, which can be as frequently as works for your use-case. Referring back to (2), since Dolt efficiently stores deltas, it shouldn't' lead to large storage footprint growth.

Let me know if this answers your questions. Would love to know more about your use-case!

**Comment by qiuwei** [comment]
@oscarbatori Thanks a lot for the detailed answers.
Our use-case is related to machine learning for financial data. I see that dolt can fit in our pipeline nicely in the following scenarios.
1. We have data providers keep pushing data into our local database, but from time to time they amend the data. 
Dolt seems to be a good fit to record the data change histor. (We are also investigating temporal tables provided by MariaDB.  
It would be nice if Doltpy can take snapshots automatically based on the binlog.)
2.  Featuring engineering is crucial for our task. The output of ETL tasks for feature engineering is of huge size, so we need to save the data along with the corresponding version of code.  This is really a headache for us because the feature engineering code is evolving quite fast. 

I have another question though:
Can people work on different branches of a  single data repo simultaneously(i.e. simultaneously make changes to different branches)?  I am asking due to that in our use-case we cannot afford to clone the data repo. So we would like to have lots of people working on a huge mono data repo but on different branches.

**Comment by qiuwei** [comment]
I did some simple benchmarks on Dolt. 
For the moment, reading data from Dolt is too slow for our use-case. 
Reading a table which contains about 160,000 rows into a pandas dataframe takes 26 seconds.
Meanwhile, [Arctic](https://github.com/man-group/arctic) enables us to read the same data within 0.5 seconds.
That is a huge difference!
Do you have any suggestions to speed up reading data from Dolt?

Many thanks!

**Comment by oscarbatori** [comment]
@qiuwei thanks for the thoughtful follow up questions.

### Use Case
Regarding your use-case, this is actually the reason I joined the company. Prior to working on Dolt/DoltHub I worked on research engineering at a quantitative hedge fund and faced precisely the problem of having data "changing under our feet" so to speak, and also of verifying vendor updates. Creating a commit graph seemed like a much better solution.

We haven't yet gotten to versioning code along with data, other than perhaps a pointer to a commit in a commit message, but this is hardly a robust solution. ETL is definitely something we need a support story for, and it's certainly in our roadmap.

I'd love to discuss this further, just to learn. If that would be of interest to you, jump on [Discord](https://discord.com/invite/RFwfYpu) and we can find one another there.

### Questions
1. Folks can definitely work on different branches concurrently, if you are running a central Dolt instance as a service having users writing to different branches via SQL is the right move
2. Regarding the slowness, are you able to share more detail on the schema and kind of data? We definitely know and are working on performance, and any detailed data point we can get on that would be helpful.

-Oscar

**Comment by qiuwei** [comment]
@oscarbatori 

I came across another very interesting project https://github.com/cwida/duckdb.
Reading data from it is lightning fast(magnitudes faster than other relational databases ). It seems they have optimized the process very well.

I have not dug into the code to find out how they achieved that, however, I think it might be interesting to you.
